questions =  [
    {"id": 0, "question": "We should deploy troops to foreign countries to secure trade routes.", "effects": {"right": 1}},
    {"id": 1, "question": "A righteous nation should spread its way of life to other nations, by military force if necessary.", "effects": {"right": 1}},
    {"id": 2, "question": "War can bring out the best in a nation.", "effects": {"right": 1}},
    {"id": 3, "question": "Wars do not need to be justified to other nations.", "effects": {"right": 1}},
    {"id": 4, "question": "Our nation has lands occupied by foreign powers that must be recovered through war.", "effects": {"right": 1}},
    {"id": 5, "question": "Supporting revolutions in other nations is a good idea.", "effects": {"right": 1}},
    {"id": 6, "question": "It is very important to maintain foreign influence.", "effects": {"right": 1}},
    {"id": 7, "question": "If done correctly, nation-building or conquest can be righteous causes.", "effects": {"right": 1}},
    {"id": 8, "question": "It is more important to maintain peaceful relations than to further out strength.", "effects": {"right": -1}},
    {"id": 9, "question": "If a military exists at all, it should be used for defence only.", "effects": {"right": -1}},
    {"id": 10, "question": "Peace is preferable to war whenever possible.", "effects": {"right": -1}},
    {"id": 11, "question": "Violence is never the answer, even in self-defence.", "effects": {"right": -1}},
    {"id": 12, "question": "Nations fighting amongst each other gets in the way of prosperity.", "effects": {"right": -1}},
    {"id": 13, "question": "Constant war destroys a society.", "effects": {"right": -1}},
    {"id": 14, "question": "World peace is a realistic goal.", "effects": {"right": -1}},
    {"id": 15, "question": "My nation is great.", "effects": {"auth": 1}},
    {"id": 16, "question": "Flag-burning is a deplorable act.", "effects": {"auth": 1}},
    {"id": 17, "question": "It is important that immigrants assimilate to our culture.", "effects": {"auth": 1}},
    {"id": 18, "question": "The United Nations should be abolished.", "effects": {"auth": 1}},
    {"id": 19, "question": "Foreign aid is a waste of money.", "effects": {"auth": 1}},
    {"id": 20, "question": "My nation’s policies do not need to be justified to other countries.", "effects": {"auth": 1}},
    {"id": 21, "question": "International law is a ridiculous concept.", "effects": {"auth": 1}},
    {"id": 22, "question": "My nation’s culture is worth preserving.", "effects": {"auth": 1}},
    {"id": 23, "question": "In the modern day, big problems can only be solved by more global unity.", "effects": {"auth": -1}},
    {"id": 24, "question": "We should have open borders.", "effects": {"auth": -1}},
    {"id": 25, "question": "Immigrants should be encouraged to maintain a distinct culture.", "effects": {"auth": -1}},
    {"id": 26, "question": "The United Nations is, or could be, a great tool for progress in the modern world.", "effects": {"auth": -1}},
    {"id": 27, "question": "No cultures are superior to others.", "effects": {"auth": -1}},
    {"id": 28, "question": "The European Parliament needs more power.", "effects": {"auth": -1}},
    {"id": 29, "question": "A united world government would be beneficial to mankind.", "effects": {"auth": -1}},
    {"id": 30, "question": "Some races are superior to others.", "effects": {"prog": 1}},
    {"id": 31, "question": "I would prefer to live around people of my own race.", "effects": {"prog": 1}},
    {"id": 32, "question": "I feel more comfortable around people with the same skin colour as me.", "effects": {"prog": 1}},
    {"id": 33, "question": "Multi-racialism is detrimental to a nation’s stability.", "effects": {"prog": 1}},
    {"id": 34, "question": "Race should be a factor in immigration.", "effects": {"prog": 1}},
    {"id": 35, "question": "Certain races should be made to disappear from within our borders.", "effects": {"prog": 1}},
    {"id": 36, "question": "Genocide is an acceptable policy if it targets an inferior race.", "effects": {"prog": 1}},
    {"id": 37, "question": "Certain races are predisposed to commit immoral acts.", "effects": {"prog": 1}},
    {"id": 38, "question": "Race is not a factor in one’s personality.", "effects": {"prog": -1}},
    {"id": 39, "question": "Interracial relationships are totally acceptable.", "effects": {"prog": -1}},
    {"id": 40, "question": "Racial diversity is a credit to a nation, not a liability.", "effects": {"prog": -1}},
    {"id": 41, "question": "All men are born equal.", "effects": {"prog": -1}},
    {"id": 42, "question": "Racism is one of the greatest sins a nation can commit.", "effects": {"prog": -1}},
    {"id": 43, "question": "I would not support a leader if I believed that he was prejudiced against another race.", "effects": {"prog": -1}},
    {"id": 44, "question": "Ethnic nationalism is unacceptable, no matter the situation.", "effects": {"prog": -1}},
    {"id": 45, "question": "Race is not a factor for me in dating or marriage.", "effects": {"prog": -1}}
];
